### ISSUE TITLE
[Universal] Subpages: Breadcrumb dividers

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#102]
![screen shot 2015-01-14 at 10 56 53 am](https://cloud.githubusercontent.com/assets/9656851/5741879/31ce5498-9bdc-11e4-9e4d-36d4743b384d.png)

We already use the vertical bar between words in the main navigation, so using it in the breadcrumbs makes them seem like a new nav menu and makes the items seem like siblings instead of a chain of decedents.

We need to change the vertical bars to "greater than" or "right single angled quote" characters.

All pages except the last in the breadcrumbs should be active links as well.

**Comment by ethanbutler** [comment]
i'm following the original design that A) jen put together and B) the client signed off on. please be more judicious about using the bug label
