### ISSUE TITLE
[Universal] Blog posts: social share icons

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#104]
![screen shot 2015-01-14 at 11 03 10 am](https://cloud.githubusercontent.com/assets/9656851/5742016/1848db82-9bdd-11e4-854f-ee5ee613b29a.png)

We need to make these active or remove/hide them for launch. The appear at both the top and bottom of single blog posts.

**Comment by ethanbutler** [comment]
already an open issue
