### ISSUE TITLE
[Universal] Values page: Blockquote

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#105]
This is missing attribution. It seems a bit shady to have an endorsement without attribution. We should verify this is intentional.

![screen shot 2015-01-14 at 11 06 01 am](https://cloud.githubusercontent.com/assets/9656851/5742085/8ad86b36-9bdd-11e4-8dda-822920dae76e.png)

**Comment by ethanbutler** [comment]
this isn't what buglists are for
