### ISSUE TITLE
[Universal] Form validation

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#107]
There doesn't appear to be any validation on forms—the can be successfully submitted without inputing anything. We should have validation (and specific user feedback messaging) for at least the following scenarios:

* Name left blank
* Email left blank
* All fields left blank
* Email not valid
* Name too short

**Comment by ethanbutler** [comment]
Resolved for everything but name too short. Some cultures just have short names, you guys.

**Comment by sposhe** [comment]
When an error message is thrown, the form disappears.

![screen shot 2015-01-15 at 8 28 11 am](https://cloud.githubusercontent.com/assets/9656851/5758133/8366f6d4-9c90-11e4-8c9f-74c6568c3f50.png)
