### ISSUE TITLE
[Universal] Search results: contextual search bar when no results

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#120]
![screen shot 2015-01-14 at 1 03 47 pm](https://cloud.githubusercontent.com/assets/9656851/5746588/968a5a0e-9bfe-11e4-9b2b-6f187fe842f4.png)
The contextual search bar is being rendered in a weird place when there are no results to a search. The container needs some extra padding.

**Comment by ethanbutler** [comment]
apparently i accidentally fixed this earlier
