### ISSUE TITLE
[PC - All browsers] Navigation - Organizational Culture

### ISSUE THREAD

**Issue by archele-cuberis** [cuberis/vivisum#127]
Whenever you select Organizational Culture from the Careers dropdown, it highlights both Org. Culture and Job Listings.

![viv_ie_orgnav](https://cloud.githubusercontent.com/assets/10440840/5747493/6e52dbee-9c06-11e4-98bd-0d8f7bbf224f.png)

**Comment by ethanbutler** [comment]
fixed. this was the weirdest bug ever
