### ISSUE TITLE
[Universal] Subpages: Intro paragraph containment

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#130]
The text on last line on intro paragraphs on subpages butts up against the graphical container it's in. Suspect this was not intentional but could be wrong.

![screen shot 2015-01-14 at 4 23 14 pm](https://cloud.githubusercontent.com/assets/9656851/5747980/3949e9de-9c0a-11e4-999f-2dae90f246a4.png)

**Comment by ethanbutler** [comment]
this actually was intentional
