### ISSUE TITLE
[iPad - Portrait: Chrome] Footer nav and logo missing

### ISSUE THREAD

**Issue by archele-cuberis** [cuberis/vivisum#135]
![img_0385](https://cloud.githubusercontent.com/assets/10440840/5748393/974521ae-9c0d-11e4-8515-d602c30686ac.PNG)

**Comment by ethanbutler** [comment]
this was on on purpose, i thought we talked about this. should that be there?

**Comment by archele-cuberis** [comment]
I haven't heard anything to suggest it shouldn't be - I'd double check with
Jennifer.

On Wed, Jan 14, 2015 at 4:56 PM, Ethan Butler <notifications@github.com>



http://cuberis.comArchele Moore
Account Manager + Marketing Strategist


919.443.2254
807 E Main St. Ste 2-210
Durham, NC 27701

http://facebook.com/cuberis



 
wrote:
