### ISSUE TITLE
[Windows7/IE9] Blog page: Main section not rendering

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#143]
Javascript that contains console.log() will not function in IE9 unless the developer tools are open. The js that applies the visible class to the appropriate content in this section isn't running, and all children are staying as "display: none;".

![bs_win7_ie_9 0 2](https://cloud.githubusercontent.com/assets/9656851/5758072/e576565e-9c8f-11e4-9f08-a508b8e926d5.jpg)

**Comment by ethanbutler** [comment]
smh at myself
