### ISSUE TITLE
[IE9–11/Desktop] Main nav: Nav shifts position during use

### ISSUE THREAD

**Issue by sposhe** [cuberis/vivisum#146]
Hovering over the nav in all versions of IE shifts it 150–200px to the left. Initially thought it may have something to do with a scrollbar appearing and triggering a unique breakpoint, but that doesn't seem to be the case. Before and after below:

![screen shot 2015-01-15 at 8 39 56 am](https://cloud.githubusercontent.com/assets/9656851/5758327/89195aa2-9c92-11e4-8815-e84a4bf9ef8b.png)

![screen shot 2015-01-15 at 8 40 06 am](https://cloud.githubusercontent.com/assets/9656851/5758329/8e922c2a-9c92-11e4-8331-2d77ec079a3f.png)

**Comment by ethanbutler** [comment]
this is fixed, and the way ie renders it kinda makes more sense than other browsers. it's not a great feeling
