### ISSUE TITLE
home CTA message after submitting

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/vivisum#40]
The Thanks message should be styled like the side bar call-out text, Merriweather bld, 24/28pt, 5d8dce

![screen shot 2015-01-07](https://cloud.githubusercontent.com/assets/10439344/5652547/944cbf72-967f-11e4-9929-08f39ded0b80.jpg)

**Comment by ethanbutler** [comment]
come back to this when we're testing this portion of the site
