### ISSUE TITLE
blog link to BLOG and MARKET RESEARCH broken

### ISSUE THREAD

**Issue by ray-cuberis** [cuberis/vivisum#50]
from...
![screen shot 2015-01-07 at 4 18 27 pm](https://cloud.githubusercontent.com/assets/10439512/5653533/00043f34-9689-11e4-8cff-018637ab8267.png)

to...
![screen shot 2015-01-07 at 4 18 19 pm](https://cloud.githubusercontent.com/assets/10439512/5653524/f01c51b0-9688-11e4-8fe5-eabb077e05a3.png)

**Comment by ethanbutler** [comment]
lol
