### ISSUE TITLE
all pages: link social media icons to appropriate sites

### ISSUE THREAD

**Issue by ray-cuberis** [cuberis/vivisum#57]
![screen shot 2015-01-07 at 5 06 54 pm](https://cloud.githubusercontent.com/assets/10439512/5654292/a1b8f846-968f-11e4-9c73-93bcd60142dc.png)

**Comment by ethanbutler** [comment]
come back to this after we get links

**Comment by sposhe** [comment]
If we're not going to link these before launch, we should hide/remove the icons.

**Comment by ethanbutler** [comment]
done. finna make a gist out of the function i wrote
