### ISSUE TITLE
[desktop Chrome] universal CTA submit behavior

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/vivisum#72]
style the "Thank you" message in same position as form fields: Merriweather bld, 22/27pt, 5d85ce

![screen shot 2015-01-13 at 10 55 27 am](https://cloud.githubusercontent.com/assets/10439344/5723640/6e29a4f2-9b13-11e4-8ae2-c896890222f1.png)
![screen shot 2015-01-13 at 11 00 29 am](https://cloud.githubusercontent.com/assets/10439344/5723642/705f89ee-9b13-11e4-84e4-b197ea965a47.png)

**Comment by ethanbutler** [comment]
resolved
