### ISSUE TITLE
[desktop Chrome] Blog landing feature post text styles

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/vivisum#73]
Author: Montserrat reg, 18/20pt, 363636
Optional author attribute and Twitter link to quote
"continue reading  >": tiny bit smaller with less tracking

![screen shot 2015-01-13 at 11 03 53 am](https://cloud.githubusercontent.com/assets/10439344/5723804/ead126a0-9b14-11e4-9e2b-4ef7c94f1f0f.png)

![screen shot 2015-01-13 at 11 03 30 am](https://cloud.githubusercontent.com/assets/10439344/5723807/ef0b66b8-9b14-11e4-8328-2ae3e6a36076.png)

**Comment by ethanbutler** [comment]
resolved locally
