### ISSUE TITLE
[desktop Chrome] universal: Blog hub pull quote tweet

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/vivisum#79]
In initial designs we said that this Twitter icon would open a window to let users share this quote as a tweet. Currently the whole box sends users to the individual post, which does include a Twitter link. Should we review this exact functionality, maybe even with the client?

**Comment by ethanbutler** [comment]
i've set this up so that it pulls the article as a shareable twitter link---i think that should work?
