### ISSUE TITLE
[desktop Chrome] Careers / Job Opening text styles

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/vivisum#87]
Please treat the job title listing similar to subhead 2, no bullets or indent, Montserrat bold, 18/26pt, 7a4e95
Reduce space between subhead2 and bullets and increase space after each bullet (see image as guide)
![screen shot 2015-01-14 at 8 57 33 am](https://cloud.githubusercontent.com/assets/10439344/5739939/ab87560a-9bcc-11e4-9dd4-6d45401fe1c1.png)

**Comment by ethanbutler** [comment]
resolved
