### ISSUE TITLE
[desktop Chrome] Search results

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/vivisum#88]
Could we use the smaller image, like in the blog hub, if there is an image in the search results?
Also, the image should be closer to its copy bock.
Reduce space between results items. See image as a guide.
![search_results](https://cloud.githubusercontent.com/assets/10439344/5740121/91b92986-9bce-11e4-9a13-6178bced977e.jpg)

**Comment by ethanbutler** [comment]
done
