### ISSUE TITLE
[desktop Chrome] Blog individual post breadcrumbs behavior

### ISSUE THREAD

**Issue by jennifer-cuberis** [cuberis/vivisum#90]
May need to review how breadcrumbs work. See example of a post linked form the Meaningful Work sorting, but breadcrumbs appear as Market Research.
![screen shot 2015-01-14 at 9 30 37 am](https://cloud.githubusercontent.com/assets/10439344/5740339/7ebad828-9bd0-11e4-882b-33d687c364bf.png)

**Comment by ethanbutler** [comment]
resolved
