### ISSUE TITLE
[iPad Mini Retina - Landscape: iOS Safari] Homepage - "Learn More" buttons 

### ISSUE THREAD

**Issue by archele-cuberis** [cuberis/vivisum#94]
Buttons in three large buckets are not aligned - middle "Learn More" dropped down further than others. 

https://mail.google.com/mail/u/0/?ui=2&ik=92abd5373b&view=att&th=14ae8eef9dbb0b9e&attid=0.1&disp=safe&zw

**Comment by ethanbutler** [comment]
this is already an open issue you guys c'mon
